export const FETCH_QUOTES = 'QUOTE/FETCH_QUOTES';
export const REQUEST_QUOTES = 'QUOTE/REQUEST_QUOTES';
export const CURRENT_PERSON = 'QUOTE/CURRENT_PERSON';
export const SET_TIMER = 'QUOTE/SET_TIMER';
export const ADD_ACTIVE_CLASSES = 'QUOTE/ADD_ACTIVE_CLASSES';
export const ADD_ANIMATE_CLASSES = 'QUOTE/ADD_ANIMATE_CLASSES';
export const REMOVE_ACTIVE_CLASSES = 'QUOTE/REMOVE_ACTIVE_CLASSES';

export const REQUEST_ITEMS = 'WIKI/REQUEST_ITEMS';
export const REQUEST_PAGE = 'WIKI/REQUEST_PAGE';
export const REQUEST_ITEM = 'WIKI/REQUEST_ITEM';
export const FETCH_ITEMS = 'WIKI/FETCH_ITEMS';
export const FILTER_NAMES = 'WIKI/FILTER_NAMES';
export const SET_CURRENT_ITEM = 'WIKI/SET_CURRENT_ITEM';
export const SET_MAX_PAGES = 'WIKI/SET_MAX_PAGES';

export const START_APP = 'START_APP';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SHOW_ERROR = 'SHOW_ERROR';
