export const FETCH_QUOTES = 'QUOTE/FETCH_QUOTES';
export const REQUEST_QUOTES = 'QUOTE/REQUEST_QUOTES';
export const CURRENT_PERSON = 'QUOTE/CURRENT_PERSON';
export const SET_TIMER = 'QUOTE/SET_TIMER';
export const ADD_ACTIVE_CLASSES = 'QUOTE/ADD_ACTIVE_CLASSES';
export const ADD_ANIMATE_CLASSES = 'QUOTE/ADD_ANIMATE_CLASSES';
export const REMOVE_ACTIVE_CLASSES = 'QUOTE/REMOVE_ACTIVE_CLASSES';

export const REQUEST_ITEMS = 'WIKI/REQUEST_ITEMS';
export const FETCH_ITEMS = 'WIKI/FETCH_ITEMS';

export const FETCH_NAMES_CHARACTERS = 'WIKI/FETCH_NAMES_CHARACTERS';
export const FETCH_NAMES_LOCATIONS = 'WIKI/FETCH_NAMES_LOCATIONS';
export const FETCH_NAMES_EPISODES = 'WIKI/FETCH_NAMES_EPISODES';

export const REQUEST_ALL_ITEMS = 'WIKI/REQUEST_ALL_ITEMS';
export const REQUEST_CHARACTERS_NAMES = 'WIKI/REQUEST_CHARACTERS_NAMES';

export const GET_ARRAY_PROPERTY = 'WIKI/GET_ARRAY_PROPERTY';

export const SET_CURRENT_PAGE = 'WIKI/SET_CURRENT_PAGE';
export const SET_CHARACTERS_MAX_PAGE = 'WIKI/SET_CHARACTERS_MAX_PAGE';
export const SET_EPISODES_MAX_PAGE = 'WIKI/SET_EPISODES_MAX_PAGE';
export const SET_LOCATIONS_MAX_PAGE = 'WIKI/SET_LOCATIONS_MAX_PAGE';

export const START_APP = 'START_APP';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SHOW_ERROR = 'SHOW_ERROR';
